name: knsbuy
description: "knsbuy is a Flutter application that allows users to check their investment portfolio, and manage their financial assets."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/
    - assets/animations/
